### ISSUE TITLE
Failed to load plugin creases (Obsidian 1.3.3, installer version)

### ISSUE THREAD

**Issue by merlinuwe** [liamcain/obsidian-creases#43]
Thanks for your great plugin.

Today I see this when starting Obsidian:

![image](https://github.com/liamcain/obsidian-creases/assets/4138869/e53986cb-b433-4247-8826-31d55208d34d)

What can I do?

**Comment by merlinuwe** [comment]
The same thing occures with Obsidian 1.3.4

![image](https://github.com/liamcain/obsidian-creases/assets/4138869/a6374e45-4da4-4a17-bd24-4bf1d2f3d5d7)

It does not occure on my Android 11 mobile phone.

**Comment by mikejlaurie** [comment]
I also get this

**Comment by Lothex91** [comment]
Same thing here!

**Comment by caglarongan** [comment]
Same thing here, it also creates vertical panes when Obsidian starts.
This goes away when I disable Creases.

<img width="1181" alt="Screenshot 2023-05-27 at 17 32 41" src="https://github.com/liamcain/obsidian-creases/assets/112904909/d7baf2c4-f1ac-4327-9779-5c4690dd28cb">

**Comment by Lothex91** [comment]
> Same thing here, it also creates vertical panes when Obsidian starts. This goes away when I disable Creases.
> 
> <img alt="Screenshot 2023-05-27 at 17 32 41" width="1181" src="https://user-images.githubusercontent.com/112904909/241400872-d7baf2c4-f1ac-4327-9779-5c4690dd28cb.png">

Yep exactly! Same issue, although I get a halfway empty panel

**Comment by caesar70** [comment]
Same issue for me also

**Comment by vaneyah** [comment]
Same issue, following this thread for resolution. Thanks.

**Comment by axelson** [comment]
I'm seeing this as well. Here's the error that I get in the console:
```
TypeError: Cannot read properties of undefined (reading 'id')
    at e (app.js:1:2124337)
    at ze.patchCoreOutlinePlugin (plugin:creases:6:37099)
    at eval (plugin:creases:6:31286)
    at t.<anonymous> (app.js:1:1923007)
    at app.js:1:236930
    at Object.next (app.js:1:237035)
    at a (app.js:1:235753)
```

Based on that I'm guessing that creases doesn't work with a change to the core outline plugin. As a temporary workaround disabling the core outline plugin appears to work well.

**Comment by RodolfoCastanheira** [comment]
Same here. Disabling the outline core plugin worked for me too. I'm using the Quiet Outline for now.

**Comment by BeverlyLaurelBLVD** [comment]
SOLUTION:

- Download the latest main.js from here: https://github.com/liamcain/obsidian-creases/releases

- Go to your obsidian vault in Finder / Filesearch

- Show hidden folders if on Mac

- Go to .obsidian (that's the name of it on mac at least)

- Go to plugins folder

- Find + open "creases"

- Place main.js in the folder

- Restart Obsidian
